### ISSUE TITLE
Running on Travis-CI fails with No such file or directory: '__init__.py'

### ISSUE THREAD

**Issue by bjmorgan** [codeclimate/python-test-reporter#40]
I am trying to use `codeclimate-test-reporter` with Travis-CI, but get the following error:
```
$ codeclimate-test-reporter --debug --token $CODECLIMATE_REPO_TOKEN
codeclimate-test-repoter 0.2.1
Requests 2.13.0
Python 3.6.1 (default, Apr 21 2017, 17:35:24) 
[GCC 4.6.3]
/home/travis/virtualenv/python3.6.1/bin/python
Linux 4.8.12-040812-genericProcessing file path=__init__.py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.1/bin/codeclimate-test-reporter", line 11, in <module>
    sys.exit(run())
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/__main__.py", line 11, in run
    sys.exit(runner.run())
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/runner.py", line 49, in run
    exit_status = reporter.run()
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/reporter.py", line 36, in run
    payload = formatter.payload()
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/formatter.py", line 20, in payload
    source_files = self.__source_files()
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/formatter.py", line 58, in __source_files
    payload = file_coverage.payload()
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 30, in payload
    "blob_id": self.__blob(),
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 56, in __blob
    contents = self.__file_body()
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 63, in __file_body
    self.file_body = read_file_content(self.__filename())
  File "/home/travis/virtualenv/python3.6.1/lib/python3.6/site-packages/codeclimate_test_reporter/components/file_coverage.py", line 16, in read_file_content
    return open(path, "r", encoding="utf-8-sig").read()
FileNotFoundError: [Errno 2] No such file or directory: '__init__.py'
```

If I run the command manually on a local machine, everything works fine:
```
[MacBook Pro bsym] $ codeclimate-test-reporter --debug
codeclimate-test-repoter 0.2.1
Requests 2.13.0
Python 3.6.1 (default, Mar 25 2017, 21:33:06) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
/Users/bjm42/.pyenv/versions/3.6.1/bin/python3.6
Darwin 16.5.0Processing file path=bsym/__init__.py
Processing file path=bsym/bsym.py
Processing file path=bsym/configuration.py
Processing file path=bsym/permutations.py
Processing file path=bsym/process.py
Processing file path=bsym/pymatgen_interface.py
Processing file path=bsym/sitelist.py
Processing file path=bsym/spacegroup.py
Processing file path=bsym/symmetry_operation.py
Submitting payload to https://codeclimate.com... CODECLIMATE_REPO_TOKEN is required and not set
done!
```

**Comment by bjmorgan** [comment]
Having poked around in the code, I think the problem is a change in the XML file produced by `coverage` going from version 4.3.4 to 4.3. 

If I generate a coverage.xml file with 4.3.4 I have entries that look like

```xml
<class branch-rate="0" complexity="0" filename="bsym/__init__.py" line-rate="1" name="__init__.py">
```

Using 4.4, I have entries that look like

```xml
<class branch-rate="0" complexity="0" filename="__init__.py" line-rate="1" name="__init__.py">
```

I haven't figure out yet exactly how the `coverage` XML file is used in the codeclimate reporter to construct the appropriate file paths, but a temporary work around is to use an earlier version of `coverage`, via `pip install coverage==4.3.4`.

**Comment by bjmorgan** [comment]
This is being discussed on the `coverage` issues [here](https://bitbucket.org/ned/coveragepy/issues/578/incomplete-file-path-in-xml-report)

**Comment by dblandin** [comment]
Hey @bjmorgan,

Thanks for the issue and context.

Would it make sense to update the `requirements.txt` file and lock down the requirement to `coverage>=4.0,<4.4` ?

**Comment by bjmorgan** [comment]
I think so. I have a version of `codeclimate-test-reporter` that now works with `coverage==4.4` for my projects (by checking the `source` element against the current working directory and prepending to the file_node `filename` attribute), but this a) breaks backwards compatibility with `coverage<4.4` and also does not get around the issue discussed [here](https://bitbucket.org/ned/coveragepy/issues/578/incomplete-file-path-in-xml-report) for more than one source directory.

https://github.com/bjmorgan/python-test-reporter/blob/coverage_path/codeclimate_test_reporter/components/formatter.py

The relevant new code is:
```python
    def __source_dir(self):
        source_dir=self.root.find("sources/source").text
        return os.path.relpath(source_dir,os.getcwd())

    def __file_nodes(self):
        source_dir=self.__source_dir()
        file_nodes=self.root.findall("packages/package/classes/class")
        if source_dir:
            [ f.set( "filename", os.path.join( source_dir, f.get("filename") ) ) for f in file_nodes ]
        return file_nodes
```

**Comment by dblandin** [comment]
Hey @bjmorgan,

I'd recommend checking out our new test reporter: https://github.com/codeclimate/test-reporter

It's decoupled from the coverage tool used to generate the report so you can manage your coverage.py usage separately.

**Comment by dblandin** [comment]
Going to go ahead and close this issue as we now emit an error from the reporter if you're using an incompatible version of coverage.py.
